package com.netrik.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Gerado com material-color-utilities 0.4.0 (SchemeTonalSpot, contraste padrão) a partir do
// seed #136B79 aprovado no design. Mesmo algoritmo do Material Theme Builder.
// success/warning: cores-base #3B8A3E e #B5651D harmonizadas com o seed (Blend.harmonize),
// tons 40/100/90/30 no claro e 80/20/30/90 no escuro.

internal val primaryLight = Color(0xFF006877)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFA2EEFF)
internal val onPrimaryContainerLight = Color(0xFF004E5A)
internal val inversePrimaryLight = Color(0xFF83D2E3)
internal val secondaryLight = Color(0xFF4A6268)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFCDE7ED)
internal val onSecondaryContainerLight = Color(0xFF334A50)
internal val tertiaryLight = Color(0xFF545D7E)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFDBE1FF)
internal val onTertiaryContainerLight = Color(0xFF3C4665)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val backgroundLight = Color(0xFFF5FAFC)
internal val onBackgroundLight = Color(0xFF171D1E)
internal val surfaceLight = Color(0xFFF5FAFC)
internal val onSurfaceLight = Color(0xFF171D1E)
internal val surfaceVariantLight = Color(0xFFDBE4E7)
internal val onSurfaceVariantLight = Color(0xFF3F484A)
internal val surfaceTintLight = Color(0xFF006877)
internal val inverseSurfaceLight = Color(0xFF2B3133)
internal val inverseOnSurfaceLight = Color(0xFFECF2F3)
internal val outlineLight = Color(0xFF6F797B)
internal val outlineVariantLight = Color(0xFFBFC8CB)
internal val scrimLight = Color(0xFF000000)
internal val surfaceBrightLight = Color(0xFFF5FAFC)
internal val surfaceDimLight = Color(0xFFD5DBDC)
internal val surfaceContainerLight = Color(0xFFE9EFF0)
internal val surfaceContainerHighLight = Color(0xFFE3E9EB)
internal val surfaceContainerHighestLight = Color(0xFFDEE3E5)
internal val surfaceContainerLowLight = Color(0xFFEFF5F6)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)

internal val primaryDark = Color(0xFF83D2E3)
internal val onPrimaryDark = Color(0xFF00363E)
internal val primaryContainerDark = Color(0xFF004E5A)
internal val onPrimaryContainerDark = Color(0xFFA2EEFF)
internal val inversePrimaryDark = Color(0xFF006877)
internal val secondaryDark = Color(0xFFB1CBD1)
internal val onSecondaryDark = Color(0xFF1C3439)
internal val secondaryContainerDark = Color(0xFF334A50)
internal val onSecondaryContainerDark = Color(0xFFCDE7ED)
internal val tertiaryDark = Color(0xFFBCC5EB)
internal val onTertiaryDark = Color(0xFF262F4D)
internal val tertiaryContainerDark = Color(0xFF3C4665)
internal val onTertiaryContainerDark = Color(0xFFDBE1FF)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF0E1416)
internal val onBackgroundDark = Color(0xFFDEE3E5)
internal val surfaceDark = Color(0xFF0E1416)
internal val onSurfaceDark = Color(0xFFDEE3E5)
internal val surfaceVariantDark = Color(0xFF3F484A)
internal val onSurfaceVariantDark = Color(0xFFBFC8CB)
internal val surfaceTintDark = Color(0xFF83D2E3)
internal val inverseSurfaceDark = Color(0xFFDEE3E5)
internal val inverseOnSurfaceDark = Color(0xFF2B3133)
internal val outlineDark = Color(0xFF899295)
internal val outlineVariantDark = Color(0xFF3F484A)
internal val scrimDark = Color(0xFF000000)
internal val surfaceBrightDark = Color(0xFF343A3C)
internal val surfaceDimDark = Color(0xFF0E1416)
internal val surfaceContainerDark = Color(0xFF1B2122)
internal val surfaceContainerHighDark = Color(0xFF252B2C)
internal val surfaceContainerHighestDark = Color(0xFF303637)
internal val surfaceContainerLowDark = Color(0xFF171D1E)
internal val surfaceContainerLowestDark = Color(0xFF090F10)

internal val successLight = Color(0xFF006D43)
internal val onSuccessLight = Color(0xFFFFFFFF)
internal val successContainerLight = Color(0xFF8AF8BA)
internal val onSuccessContainerLight = Color(0xFF005231)
internal val successDark = Color(0xFF6DDBA0)
internal val onSuccessDark = Color(0xFF003921)
internal val successContainerDark = Color(0xFF005231)
internal val onSuccessContainerDark = Color(0xFF8AF8BA)

internal val warningLight = Color(0xFF855400)
internal val onWarningLight = Color(0xFFFFFFFF)
internal val warningContainerLight = Color(0xFFFFDDB7)
internal val onWarningContainerLight = Color(0xFF653E00)
internal val warningDark = Color(0xFFFFB95E)
internal val onWarningDark = Color(0xFF472A00)
internal val warningContainerDark = Color(0xFF653E00)
internal val onWarningContainerDark = Color(0xFFFFDDB7)
